<!-- <div class="w3-main w3-container" style="margin-top: 30px">

	<?= $this->flashSession->output(); ?>
	<?= $this->getContent(); ?>
	 
    <div id="listProductsModal" class="w3-modal">
		<div class="w3-modal-content">
			<div class="w3-container">
				<span onclick='$("#listProductsModal").hide()' class="w3-button w3-display-topright">&times;</span>
				<input type="hidden" id="listProductsLink" value="<?php echo $this->url->get('products/list') ?>" />
				<div id="listProductsTable">
					xxxx
				</div>
			</div>
		</div>
   	</div>

	<form action="" method="post" accept-charset="utf-8" id="formThanhPham">
		<input type="hidden" value="<?= $this->url->get('products/vatTuSanPham') ?>" id="linkSendVatTu">
		<input type="hidden" value="<?= $this->url->get('products/ajaxProduct') ?>" id="addLinkSendAjax">
		<input type="hidden" name="idCtProducts" id="idCtProducts" value="">

    	<div class="w3-section overflowHidden">
	        <div class="w3-col l4 m4 padding-right10px">     
	          	<label class="w3-text-green"><b>Mã T.Phẩm:</b></label>
	          	<input type="text" class="width100 validateFiled" name="maThanhPham" id="maThanhPham" value="<?= $thanhPham->Products->maSanPham ?>"> &nbsp; 
				<label class="w3-text-green"><b> Số lượng:</b></label>
	          	<input type="number" class="width80 validateFiled" name="soLuongThanhPham" id="soLuongThanhPham" value="<?= $thanhPham->soLuongThanhPham ?>" onchange="lonHonZero(this)">
	          	<button id="btnSoLuong" type="button" class="w3-green w3-hover-gray">
	          		ok
	          	</button>
	        </div>
	        <div class="w3-col l8 m8">    
	          	<span class="w3-text-green"><b>Tên Thành Phẩm: </b></span>
	          	<span type="text" name="tenThanhPham" class="w3-bold" id="tenThanhPham"><?= $thanhPham->Products->tenSanPham ?></span>
	        </div>
		</div>
		
	   <table id="addTable" class="w3-table-all w3-bordered w3-border">
			<thead>
				<tr class="w3-red">
					<th>STT</th>
					<th>Mã Vật Tư</th>
					<th>Tên Vật Tư</th>
					<th>SL Vật Tư</th>
					<th>Tổng SL VT</th>
					<th>SL Phát Sinh</th>
					<th>Lý do / Ghi chú</th>
					<th>Tồn H.Tại</th>
					<th>Tồn Cuối Kỳ</th>
					<th>Xóa</th>
				</tr>
			</thead>
			<tbody>

				<?php $countCtproducts = count($thanhPham->Products->Ctproducts); ?>

				<?php if ($countCtproducts > 0) :?>

					<?php for($i = 0; $i < $countCtproducts; $i++): ?>

							<tr class="addTrTable">
								<input class="idCtVatTuThanhPham" type="hidden" name="idCtVatTuThanhPham[]" value="<?= $ctthanhPham[$i]->id ?>">
				
								<input class="idMaVatTu" type="hidden" name="idMaVatTu[]" value="<?= $ctthanhPham[$i]->idCtProducts ?>">
								
								<td class="stt"><?= $i + 1 ?></td>
								<td><?= $ctthanhPham[$i]->Products->maSanPham ?></td>
								
								<td class="tenSP"><?= $ctthanhPham[$i]->Products->tenSanPham ?></td>
								
								<td class="slVatTu"><?= $ctthanhPham[$i]->soLuongVatTu / $thanhPham->soLuongThanhPham ?></td>
								
								<td class="tongSLVatTu"><?= $ctthanhPham[$i]->soLuongVatTu ?></td>
								
								<td><input class="soLuongPhatSinh" type ="number" name="soLuongPhatSinh[]" value="<?= $ctthanhPham[$i]->soLuongThem ?>" onchange="changeSoLuongPhatSinh(this)"></td>
								
								<td><input class="ghiChu" type ="text" name="ghiChuCtthanhPham[]" value="<?= $ctthanhPham[$i]->ghiChu ?>"></td>
								
								<td class="tonHienTai"><?= $ctPhieuXuatKho[$i]->tonDauKy ?></td>
								<td class="tonCuoiKy"><?= $ctPhieuXuatKho[$i]->tonCuoiKy ?></td>
								
								<td><a href="#" title="Xóa sản phẩm này" class="w3-text-red"></a></td>
							</tr>

					<?php endfor ?>
				<?php endif ?>

				<?php for($j = $countCtproducts; $j < count($ctthanhPham); $j++) :?>

					<tr class="addTrTable">
	
						<input class="idCtVatTuThanhPham" type="hidden" name="idCtVatTuThanhPham[]" value="<?= $ctthanhPham[$j]->id ?>">
						
						<input class="idMaVatTu" type="hidden" name="idMaVatTu[]" value='<?= $ctthanhPham[$j]->idCtProducts ?>'>
						
						<td class="stt"><?= $j + 1 ?></td>
						<td><?= $ctthanhPham[$j]->Products->maSanPham ?></td>
						
						<td class="tenSP"><?= $ctthanhPham[$j]->Products->tenSanPham ?></td>
						
						<td>----</td>
						
						<td><input class="soLuongPhatSinh" type ="number" name="soLuongPhatSinh[]" value="<?= $ctthanhPham[$j]->soLuongVatTu ?>" onchange="changeSoLuong(this)"></td>
						
						<td><input class="ghiChu" type ="text" name="ghiChuCtthanhPham[]" value="<?= $ctthanhPham[$j]->ghiChu ?>"></td>
						
						<td class="tonHienTai"><?= $ctPhieuXuatKho[$j]->tonDauKy ?></td>
						<td class="tonCuoiKy"><?= $ctPhieuXuatKho[$j]->tonCuoiKy ?></td>
						
						<td><a href="#" title="Xóa sản phẩm này" class="w3-text-red" onclick="deleteTr(this)">✘</a></td>
					
					</tr>
				<?php endfor ?>

				<tr class="addMaSanPham">
					<td class="stt-add">1</td>
					<td colspan="9">
						<input type="text" id="addMaSanPham" value="" placeholder="Nhập mã sản phẩm">
						<button id="btnChonSanPham" type="button" class="w3-green w3-hover-gray"><i class="fa fa-search" aria-hidden="true"></i></button>
					</td>
				</tr>
			</tbody>
	   </table>
	   
  	<div class="w3-section"><button id="submit" class="w3-btn w3-green checkSL">Edit</button></div>
	</form>
</div> -->