<div class="w3-main">

	<div id="listProductsModal" class="w3-modal">
		<div class="w3-modal-content">
			<div class="w3-container">
				<span onclick='$("#listProductsModal").hide()' class="w3-button w3-display-topright">&times;</span>
				<input type="hidden" id="listProductsLink" value="<?php echo $this->url->get('products/list') ?>" />
				<div id="listProductsTable">
					xxxx
				</div>
			</div>
		</div>
   	</div>

	<form action="" method="post" accept-charset="utf-8" id="formThanhPham">
		<input type="hidden" value="<?= $this->url->get('products/vatTuSanPham') ?>" id="linkSendVatTu">
		<input type="hidden" value="<?= $this->url->get('products/ajaxProduct') ?>" id="addLinkSendAjax">
		<input type="hidden" name="idCtProducts" id="idCtProducts" value="">

    	<div class="w3-section overflowHidden">
	        <div class="w3-col l4 m4 padding-right10px">     
	          	<label class="w3-text-green"><b>Mã T.Phẩm: <span class="required">(*)</span></b></label>
	          	<input type="text" class="width100 validateFiled" name="maThanhPham" id="maThanhPham" value=""> &nbsp; 
				<label class="w3-text-green"><b> Số lượng:</b></label>
	          	<input type="number" class="width80 validateFiled" name="soLuongThanhPham" id="soLuongThanhPham" value="1" onchange="lonHonZero(this)">
	          	<button id="btnChonThanhPham" type="button" class="w3-green w3-hover-gray">
	          		ok
	          	</button>
	        </div>
	        <div class="w3-col l8 m8">    
	          	<span class="w3-text-green"><b>Tên Thành Phẩm: </b></span>
	          	<span type="text" name="tenThanhPham" class="w3-bold" id="tenThanhPham"></span>
	        </div>
		</div>
		
	   <table id="addTable" class="w3-table-all w3-bordered w3-border">
			<thead>
				<tr class="w3-red">
					<th>STT</th>
					<th>Mã Vật Tư</th>
					<th>Tên Vật Tư</th>
					<th>SL Vật Tư</th>
					<th>Tổng SL VT</th>
					<th>SL Phát Sinh</th>
					<th>Lý do / Ghi chú</th>
					<th>Tồn H.Tại</th>
					<th>Tồn Cuối Kỳ</th>
					<th>Xóa</th>
				</tr>
			</thead>
			<tbody>
				<tr class="addMaSanPham">
					<td class="stt-add">1</td>
					<td colspan="9">
						<input type="text" id="addMaSanPham" value="" placeholder="Nhập mã sản phẩm">
						<button id="btnChonSanPham" type="button" class="w3-green w3-hover-gray"><i class="fa fa-search" aria-hidden="true"></i></button>
					</td>
				</tr>
			</tbody>
	   </table>
	   
  	<div class="w3-section"><button id="submit" class="w3-btn w3-green checkSL">Nhập</button></div>
	</form>
</div>

<div class="w3-row padding-bottom10px padding-top10px">
	<input type="hidden" value="<?= $this->url->get('thanhpham/index') ?>" id="linkIndex">
	<input type="hidden" value="<?= $this->url->get('thanhpham/ajaxSearch') ?>" id="linkSendAjax">
	<input type="hidden" value="<?= $this->url->get('thanhpham/edit/') ?>" id="linkEdit">
	<input type="hidden" value="<?= $this->url->get('thanhpham/delete/') ?>" id="linkDelete">
	<div class="w3-col l2 m2 s3 filter-limit">
		
		<span class="name-filter">Limit:</span>
		
		<?php 
		$limtSelector = new Phalcon\Forms\Element\Select('limit', [
				"25" 		=> "25",
				"50"  		=> "50",
				"100"  		=> "100",
				"200" 		=> "200",
				"500" 		=> "500",
				"1000" 		=> "1,000",
		], ['using'    => ["id", "name"] ]);
		
		$limtSelector->setDefault($limit);
		
		echo $limtSelector->render();
		?>
	</div>
	<div class="w3-col l5 m5 s9 filter-search">
		<span class="name-filter">Filter: </span> 
		<input type="search" name="filterRows" value="<?= $filterRows; ?>" placeholder="Search this table">
		<button type="button" id="btnResetFilter" class="buttonX">x</button>
		<button type="submit" class="w3-green submit" id="btnFilter">Filter</button>
	</div>
	<div class="w3-col l5 filter-date">
		<span class="name-filter">Ngày: </span> 
		<input type="date" name="dateStart" value="<?= date("Y-m-d") ?>">
		<input type="date" name="dateEnd" value="<?= date("Y-m-d") ?>">
		<button type="button" class="w3-green submit" id="btnDate">Gửi</button>
	</div>
</div>

<div class="w3-responsive">
	<table id="table-show" class="w3-table-all">
		<thead>
		  	<tr class="w3-blue">
				<th>STT</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Ngày
					<input type="hidden" name="ngay" value="ngay ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Tên Sản Phẩm
					<input type="hidden" name="tenSanPham" value="tenSanPham ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Số Lượng Thành Phẩm
					<input type="hidden" name="soLuongThanhPham" value="soLuongThanhPham ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Tổng SL Vật Tư
					<input type="hidden" name="tongSoLuongVatTu" value="tongSoLuongVatTu ASC">
					</a>
				</th>
				<th>Các Mã Hàng</th>
				
		  	</tr>
		</thead>
		<tbody class="tbody">
			
		</tbody>
		
		<tfoot>
	        <tr>
	            <td colspan="7" align="right">
					<div class="w3-bar w3-center" id="pagination">
						
					</div>
	            </td>
	        </tr>
	    </tfoot>
		
	</table>
</div>
