<div class="w3-main w3-container">
	<?= $this->flashSession->output(); ?>
	<?= $this->getContent(); // Thông báo lỗi chung?>

	<div class="w3-responsive">
		<div id="customersModal" class="w3-modal">
			<div class="w3-modal-content">
				<div class="w3-container">
					<span onclick='$("#customersModal").hide()' class="w3-button w3-display-topright">&times;</span>
					<input type="hidden" id="listCustomerLink" value="<?php echo $this->url->get('customers/list') ?>" />
					<div id="customersTable">
						xxxx
					</div>
				</div>
			</div>
		</div>

        <div class="listNhaCungCapModal w3-modal">
            <div class="w3-modal-content">
                <div class="w3-container">
                    <span onclick='$(".listNhaCungCapModal").hide()' class="w3-button w3-display-topright">&times;</span>
                    <input type="hidden" id="listNhaCungCapLink" value="<?php echo $this->url->get('nhacungcap/list') ?>" />
                    <div id="listNhaCungCapTable">
                        xxxx
                    </div>
                </div>
            </div>
        </div>
	</div>

    <form action="" method="post" accept-charset="utf-8">
    	<div class="overflowHidden">
    		<div class="form-group">    
    			<label class="w3-text-green"><b>Nội Dung</b></label>
    			<?php echo $form->render('noiDung', array('class' => 'w3-input w3-border')); ?>
    		</div>

    		<div>
    			<div class="w3-third">
    				<div class="form-group row-inline">    
    					<label class="w3-text-green"><b>Số Tiền</b></label>
    					<?php echo $form->render('soTien', array('class' => 'w3-input w3-border keyUpFormatAmount')); ?>
    				</div>
    				<div class="form-group row-inline">      
    					<label class="w3-text-green"><b>Hình Thức</b></label>
    					<?php echo $form->render('hinhThuc', array('class' => 'hinhThuc w3-input w3-border')); ?>
    				</div>
    			</div>
    			<div class="w3-third padding-right-left">
    				<div class="form-group">      
    					<label class="w3-text-green"><b>Nguồn Thu</b></label>
    					<?php echo $form->render('nguonThu', array('class' => 'w3-input w3-border')); ?>
    				</div>
    				<div class="form-group">
    					<label class="w3-text-green"><b>Tên Ngân Hàng</b></label>

    					<?php if (!empty($qltc->ckNganHang)): ?>

    						<input type="text" name="ckNganHang" class="tenNganHang w3-input w3-border w3-light-gray"  disabled="disabled" style="display: none">
    						<?php echo $form->render('ckNganHang', array('class' => 'ckNganHang w3-input w3-border')); ?>

    					<?php else: ?>

    						<input type="text" name="ckNganHang" class="tenNganHang w3-input w3-border w3-light-gray"  disabled="disabled">
    						<?php echo $form->render('ckNganHang', array('class' => 'ckNganHang w3-input w3-border' , 'disabled' => 'disabled' , 'style' => 'display:none')); ?>

    					<?php endif ?>
    				</div>
    			</div>

    			<div class="w3-third">

    				<div id="input-khachHang" class="form-group" style="<?= isset($qltc->NhaCungCap->tenNhaCungCap) ? 'display: none' : '' ?>">
    					<?php echo $form->render('idKhachHang', array('class' => 'w3-input w3-border idKhachHang')); ?>
    					<label class="w3-text-green"><b>Tên Khách Hàng</b></label>
    					<input type="text" name="tenKhachHang" id="tenKhachHang" class="w3-input w3-border w3-light-gray tenKhachHang" value="<?= isset($qltc->Customers->tenKhachHang) ? $qltc->Customers->tenKhachHang : '' ?>" disabled>
    				</div>
                    <div id="input-nhaCungCap" class="form-group" style="<?= isset($qltc->NhaCungCap->tenNhaCungCap) ? '' : 'display: none' ?>">
                        <input type="hidden" name="idNhaCungCap" id="idNhaCungCapThu" class="w3-input w3-border idNhaCungCap" value="<?= $qltc->idNhaCungCap ?>">
                        <label class="w3-text-green"><b>Nhà Cung Cấp</b></label>
                        <input type="text" name="tenNhaCungCap" class="w3-input w3-border w3-light-gray tenNhaCungCap" value="<?= isset($qltc->NhaCungCap->tenNhaCungCap) ? $qltc->NhaCungCap->tenNhaCungCap : '' ?>" disabled>
                    </div>
    				<div class="form-group">     
    					<label class="w3-text-green"><b>Ghi Chú</b></label>
    					<?php echo $form->render('ghiChu', array('class' => 'w3-input w3-border')); ?>
    				</div>
    			</div>
    		</div>
    	</div>
	  	<div class="w3-section"><button class="w3-btn w3-green">Edit</button></div>
	</form>
</div>