<div class="w3-row padding-bottom10px padding-top10px">

	<input type="hidden" value="<?= $this->url->get('nhacungcap/index') ?>" id="linkIndex">
	<input type="hidden" value="<?= $this->url->get('nhacungcap/ajaxSearch') ?>" id="linkSendAjax">
	<input type="hidden" value="<?= $this->url->get('nhacungcap/edit/') ?>" id="linkEdit">
	<input type="hidden" value="<?= $this->url->get('nhacungcap/delete/') ?>" id="linkDelete">
	<div class="w3-col l2 m2 s3 filter-limit">
		
		<span class="name-filter">Limit:</span>
		
		<?php 
		$limtSelector = new Phalcon\Forms\Element\Select('limit', [
				"25" 		=> "25",
				"50"  		=> "50",
				"100"  		=> "100",
				"200" 		=> "200",
				"500" 		=> "500",
				"1000" 		=> "1,000",
		], ['using'    => ["id", "name"] ]);
		
		$limtSelector->setDefault($limit);
		
		echo $limtSelector->render();
		?>
	</div>
	<div class="w3-col l5 m5 s9 filter-search">
		<span class="name-filter">Filter: </span> 
		<input type="search" name="filterRows" value="<?= $filterRows; ?>" placeholder="Search this table">
		<button type="button" id="btnResetFilter" class="buttonX">x</button>
		<button type="submit" class="w3-green submit" id="btnFilter">Filter</button>
	</div>
</div>

<div class="w3-responsive">
	<table id="table-show" class="w3-table-all">
		<thead>
		  	<tr class="w3-blue">
				<th>STT</th>
				<?php if ($this->view->duocXoa) { echo "<th>Xóa</th>";} ?>
				<th><a class="orderColumn width200px" onclick="orderBy(this)">Tên Nhà Cung Cấp
					<input type="hidden" name="tenNhaCungCap" value="tenNhaCungCap ASC">
					</a>
				</th>
				<th><a class="orderColumn width100px" onclick="orderBy(this)">Số Đơn Hàng
					<input type="hidden" name="soDonHang" value="soDonHang ASC">
					</a>
				</th>
				
				<th><a class="orderColumn" onclick="orderBy(this)">Công Nợ
					<input type="hidden" name="congNo" value="congNo ASC">
					</a>
				</th>
				
				<th><a class="orderColumn width200px" onclick="orderBy(this)">Địa Chỉ
					<input type="hidden" name="diaChi" value="diaChi ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Liên Hệ
					<input type="hidden" name="lienHe" value="lienHe ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Mô Tả
					<input type="hidden" name="moTa" value="moTa ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Ghi Chú
					<input type="hidden" name="ghiChu" value="ghiChu ASC">
					</a>
				</th>
		  	</tr>
		</thead>
		<tbody class="tbody">
		
		</tbody>
		
		<tfoot>
	        <tr>
	            <td colspan="7" align="right">
					<div class="w3-bar w3-center" id="pagination">
						
					</div>
	            </td>
	        </tr>
	    </tfoot>
		
	</table>
</div>
<div class="w3-row">
	<div class="w3-right-align" style="background: #000;padding: 10px;color: #fff">
		<b>Tổng Tiền:</b> <span class='tongCongNo'></span>
	</div>
</div>