<div class="w3-main">
	<div id="listProductsModal" class="w3-modal">
		<div class="w3-modal-content">
			<div class="w3-container">
				<span onclick='$("#listProductsModal").hide()' class="w3-button w3-display-topright">&times;</span>
				<input type="hidden" id="listProductsLink" value="<?php echo $this->url->get('products/list') ?>" />
				<div id="listProductsTable">
					xxxx
				</div>
			</div>
		</div>
   </div>

   	<div class="listNhaCungCapModal w3-modal">
		<div class="w3-modal-content">
			<div class="w3-container">
				<span onclick='$(".listNhaCungCapModal").hide()' class="w3-button w3-display-topright">&times;</span>
				<input type="hidden" id="listNhaCungCapLink" value="<?php echo $this->url->get('nhacungcap/list') ?>" />
				<div id="listNhaCungCapTable">
					xxxx
				</div>
			</div>
		</div>
   	</div>

    <form action="" method="post" accept-charset="utf-8">
		<input type="hidden" value="<?= $this->url->get('products/ajaxProduct') ?>" id="addLinkSendAjax">
		<input type="hidden" value="<?= $this->url->get('dathang/ajaxDuyetChi') ?>" id="linkSendDuyetChi">
    		
    		<div class="row w3-row-padding">

	    		<div class="w3-col l2 m4">
	    			<?php echo $form->render('idNhaCungCap', array('class' => 'w3-input w3-border idNhaCungCap validateFiled')); ?>
	    			<label class="w3-text-green"><b>Nhà Cung Cấp</b><span class="required">(*)</span></label>
					<input type="text" name="tenNhaCungCap" class="tenNhaCungCap" value="" disabled>
					<button id="btnChonNhaCungCap" type="button" class="buttonX w3-green w3-hover-gray"><i class="fa fa-search" aria-hidden="true"></i></button>
	    		</div>
          <div class="w3-col l4 m4">
              <label class="w3-text-green"><b>Nội Dung</b><span class="required">(*)</span></label>
              <?php echo $form->render('noiDung', array('class' => 'w3-input w3-border validateFiled')); ?>
          </div>

	    		<div class="w3-col l4 m4">
	    			<label class="w3-text-green"><b>Ghi Chú</b></label>
			   		<?php echo $form->render('ghiChu', array('class' => 'w3-input w3-border', 'rows' => 1)); ?>
	    		</div>
	    		
				<br>
               
               <table id="addTable" class="w3-table-all w3-bordered w3-border w3-margin-top">
                    <thead>
                         <tr class="w3-red">
                           <th>STT</th>
                           <th>Mã SP</th>
                           <th>Tên Sản Phẩm</th>
                           <th>Số Lượng</th>
                           <th>Đơn Giá</th>
                           <th>Thành Tiền</th>
                           <th>Ghi Chú</th>
                           <th>Tồn Kho</th>
                           <th>Xóa</th>
                         </tr>
                    </thead>
                    <tbody>
                         <tr class="addMaSanPham">
                              <td class="stt-add">1</td>
                              <td colspan="8"><input type="text" id="addMaSanPham" name="addMaSanPham" value="" placeholder="Nhập mã sản phẩm">
                              <button id="btnChonSanPham" type="button" class="w3-green w3-hover-gray"><i class="fa fa-search" aria-hidden="true"></i></button>
                              </td>
                         </tr>
                         <tr>
							  <td colspan="5">
								<label for="">Xuất Hóa Đơn</label>
								<?php echo $form->render('coXuatHoaDonKhong', array('class' => 'w3-check' , 'value' => '1')); ?>
							  </td>
							  <td>Tổng Cộng Chưa VAT:</td>
							  <td><input type="text" name="tongCongChuaVAT" value="0" id="tongCongChuaVAT" readonly="true" class="w3-right-align"></td>
							  <td> <td>
                         </tr>
                         <tr class="thuevat" style="display: none">
                              <td colspan="5"></td>
                              <td>Thuế VAT:</td>
                              <td><input type="text" name="thueVAT" value="0" id="thueVAT" readonly="true" class="w3-right-align"></td>
							  <td> <td>
                         </tr>
                         <tr class="sum">
                              <td colspan="5"></td>
                              <td>Tổng Tiền:</td>
                              <td><input type="text" name="tongTienThanhToan" value="0" id="tongTienThanhToan" readonly="true" class="w3-right-align"></td>
							  <td> <td>
                         </tr>
                    </tbody>
               	</table>
               <br>

    		</div>

  		<div class="w3-section"><button id="submit" class="w3-btn w3-green">Đăng ký</button></div>
	</form>
</div>