<div class="w3-row padding-bottom10px padding-top10px">
    <input type="hidden" value="<?= $this->url->get('dathang/index') ?>" id="linkIndex">
	<input type="hidden" value="<?= $this->url->get('dathang/ajaxSearch') ?>" id="linkSendAjax">
	<input type="hidden" value="<?= $this->url->get('dathang/edit/') ?>" id="linkEdit">
	<input type="hidden" value="<?= $this->url->get('dathang/delete/') ?>" id="linkDelete">
	<div class="w3-col l2 m4 s2 filter-limit">
		
		<span class="name-filter">Limit:</span>
		
		<?php 
		$limtSelector = new Phalcon\Forms\Element\Select('limit', [
				"25" 		=> "25",
				"50"  		=> "50",
				"100"  		=> "100",
				"200" 		=> "200",
				"500" 		=> "500",
				"1000" 		=> "1,000",
		]);
		
		$limtSelector->setDefault($limit);
		
		echo $limtSelector->render();
		?>
	</div>
	
	<div class="w3-col l5 m8 s10 filter-search">
		<span class="name-filter">Filter: </span> 
		<input type="search" name="filterRows" value="<?= $filterRows; ?>" placeholder="Search this table">
		<button type="button" id="btnResetFilter" class="buttonX" >x</button>
		<button type="button" id="btnFilter" class="w3-green submit" >Filter</button>
	</div>
	<div class="w3-col l5 filter-date">
		<span class="name-filter">Ngày: </span> 
		<input type="date" name="dateStart" value="<?= date("Y-m-d") ?>">
		<input type="date" name="dateEnd" value="<?= date("Y-m-d") ?>">
		<button type="button" class="w3-green submit" id="btnDate">Gửi</button>
	</div>
</div>
<div class="w3-responsive" id="drag-scroll">
	<table id="table-show" class="w3-table-all">
		<thead>
		  	<tr class="w3-blue">
				<th>STT</th>
				<?php if ($this->view->duocXoa) { echo "<th>Xóa</th>";} ?>
				<th><a class="orderColumn width100px" onclick="orderBy(this)">Ngày
					<input type="hidden" name="ngay" value="ngay ASC">
					</a>
				</th>
				<th><a class="orderColumn width200px" onclick="orderBy(this)">Tên Nhà Cung Cấp
					<input type="hidden" name="tenNhaCungCap" value="tenNhaCungCap ASC">
					</a>
				</th>
				<th class="width100px">Mã SP</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Công Nợ
					<input type="hidden" name="congNo" value="congNo ASC">
					</a>
				</th>
				<th><a class="orderColumn width100px" onclick="orderBy(this)">Tổng Cộng Chưa VAT
					<input type="hidden" name="tongCongChuaVAT" value="tongCongChuaVAT ASC">
					</a>
				</th>
				<th class="w3-center"><a class="orderColumn" onclick="orderBy(this)">Thuế VAT
					<input type="hidden" name="thueVAT" value="thueVAT ASC">
					</a>
				</th>
				<th><a class="orderColumn width100px" onclick="orderBy(this)">Tổng tiền thanh toán
					<input type="hidden" name="tongTienThanhToan" value="tongTienThanhToan ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Nhập Kho
					<input type="hidden" name="nhapKho" value="nhapKho ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Trạng Thái
					<input type="hidden" name="trangThai" value="trangThai ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Người Nhập
					<input type="hidden" name="name" value="name ASC">
					</a>
				</th>
				<th></th>
				<th>Ghi Chú</th>
				
		  	</tr>
		</thead>
		<tbody class="tbody">
		
		</tbody>
		<tfoot>
	        <tr>
	            <td colspan="11" align="right">
					<div class="w3-bar w3-center" id="pagination">
						
					</div>
	            </td>
	        </tr>
	    </tfoot>
	</table>
</div>
