<div class="w3-main w3-container">
    <?= $this->flashSession->output(); ?>
	<?= $this->getContent(); // Thông báo lỗi chung?>
    <form action="" method="post" accept-charset="utf-8">
	  <div class="overflowHidden">
	        <div class="form-group">    
	          	<label class="w3-text-green"><b>Tên Nhà Xe <span class="required">(*)</span></b></label>
	          	<?php echo $form->render('tenNhaXe', array('class' => 'w3-input w3-border validateFiled')); ?>
	        </div>
	        <div class="form-group">     
	          	<label class="w3-text-green"><b>Địa Chỉ <span class="required">(*)</span></b></label>
	          	<?php echo $form->render('diaChi', array('class' => 'w3-input w3-border validateFiled')); ?>
	        </div>
			
			<div>
				<div class="w3-half">
					<div class="form-group">     
					  	<label class="w3-text-green"><b>Lộ Trình Đi <span class="required">(*)</span></b></label>
					  	<?php echo $form->render('loTrinhDi', array('class' => 'w3-input w3-border validateFiled')); ?>
					</div>
					
					<div class="form-group">      
					  	<label class="w3-text-green"><b>Lộ Trình Đến <span class="required">(*)</span></b></label>
					  	<?php echo $form->render('loTrinhDen', array('class' => 'w3-input w3-border validateFiled')); ?>
					</div>

					<div class="form-group">      
					  	<label class="w3-text-green"><b>Số Điện Thoại <span class="required">(*)</span></b></label>
					  	<?php echo $form->render('soDienThoai', array('class' => 'w3-input w3-border validateFiled')); ?>
					</div>
				</div>
				<div class="w3-half padding-left10px padding-none">
					
					<div class="form-group">     
					  	<label class="w3-text-green"><b>Ghi Chú</b></label>
					  	<?php echo $form->render('ghiChu', array('class' => 'w3-input w3-border', 'rows' =>'7')); ?>
					</div>
				</div>
			</div>
	    </div>
	  <div class="w3-section"><button id="submit" class="w3-btn w3-green">Edit</button></div>
	</form>
</div>