<div class="w3-row padding-bottom10px padding-top10px">
	<input type="hidden" value="<?= $this->url->get('nhaxe/index') ?>" id="linkIndex">
	<input type="hidden" value="<?= $this->url->get('nhaxe/ajaxSearch') ?>" id="linkSendAjax">
	<input type="hidden" value="<?= $this->url->get('nhaxe/edit/') ?>" id="linkEdit">
	<input type="hidden" value="<?= $this->url->get('nhaxe/delete/') ?>" id="linkDelete">
	<div class="w3-col l2 m4 s2 filter-limit">
		
		<span class="name-filter">Limit:</span> 
		
		<?php 
		$limtSelector = new Phalcon\Forms\Element\Select('limit', [
				"25" 		=> "25",
				"50"  		=> "50",
				"100"  		=> "100",
				"200" 		=> "200",
				"500" 		=> "500",
				"1000" 		=> "1,000",
		], ['using'    => ["id", "name"] ]);
		
		$limtSelector->setDefault($limit);
		
		echo $limtSelector->render();
		?>
	</div>
	<div class="w3-col l5 m8 s10 filter-search">
		<input type="search" name="filterRows" value="<?= $filterRows; ?>" placeholder="Search this table">
		<button type="button" id="btnResetFilter" class="buttonX">x</button>
		<button type="submit" class="w3-green submit" id="btnFilter">Filter</button>
	</div>
	<div class="w3-col l5 filter-date">
		<span class="name-filter">Đi: </span>
		<input type="text" name="filterLoTrinhDi" value="" class="input-mobile" placeholder="Lộ Trình Đi">
		<span class="name-filter">Đến: </span>
		<input type="text" name="filterLoTrinhDen" value="" class="input-mobile" placeholder="Lộ Trình Đến">
		<button type="button" class="w3-green submit" id="btnLoTrinh">Gửi</button>
	</div>
</div>

<div class="w3-responsive">
	<table id="table-show" class="w3-table-all">
		<thead>
		  	<tr class="w3-blue">
				<th>STT</th>
				<?php if ($this->view->duocXoa) { echo "<th>Xóa</th>";} ?>
				<th><a class="orderColumn" onclick="orderBy(this)">Tên Nhà Xe
					<input type="hidden" name="tenNhaXe" value="tenNhaXe ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Lộ Trình Đi
					<input type="hidden" name="loTrinhDi" value="loTrinhDi ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Lộ Trình Đến
					<input type="hidden" name="loTrinhDen" value="loTrinhDen ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Số Điện Thoại
					<input type="hidden" name="soDienThoai" value="soDienThoai ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Địa Chỉ
					<input type="hidden" name="diaChi" value="diaChi ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Ghi Chú
					<input type="hidden" name="ghiChu" value="ghiChu ASC">
					</a>
				</th>	
		  	</tr>
		</thead>
		<tbody class="tbody">
		
		</tbody>

		<tfoot>
	        <tr>
	            <td colspan="9" align="right">
					<div class="w3-bar w3-center" id="pagination">
						
					</div>
	            </td>
	        </tr>
	    </tfoot>
	</table>
</div>