<div class="w3-row padding-bottom10px padding-top10px">
	<input type="hidden" value="<?= $this->url->get('quanlychiphi/index') ?>" id="linkIndex">
	<input type="hidden" value="<?= $this->url->get('quanlychiphi/ajaxSearch') ?>" id="linkSendAjax">
	<input type="hidden" value="<?= $this->url->get('quanlychiphi/edit/') ?>" id="linkEdit">
	<input type="hidden" value="<?= $this->url->get('quanlychiphi/delete/') ?>" id="linkDelete">
	<input type="hidden" value="<?= $this->url->get('quanlychiphi/ajaxDuyetChi') ?>" id="linkSendDuyetChi">
	<div class="w3-col l2 m4 s2 filter-limit">
		
		<span class="name-filter">Limit:</span>
		
		<?php 
		$limtSelector = new Phalcon\Forms\Element\Select('limit', [
				"25" 		=> "25",
				"50"  		=> "50",
				"100"  		=> "100",
				"200" 		=> "200",
				"500" 		=> "500",
				"1000" 		=> "1,000",
		], ['using'    => ["id", "name"] ]);
		
		$limtSelector->setDefault($limit);
		
		echo $limtSelector->render();
		?>
	</div>
	<div class="w3-col l5 m8 s10 filter-search">
		<span class="name-filter">Filter: </span>
		<input type="search" name="filterRows" value="<?= $filterRows; ?>" placeholder="Search this table">
		<button type="button" id="btnResetFilter" class="buttonX">x</button>
		<button type="submit" class="w3-green submit" id="btnFilter">Filter</button>
	</div>
	<div class="w3-col l5 filter-date">
		<span class="name-filter">Ngày: </span> 
		<input type="date" name="dateStart" value="<?= date("Y-m-d") ?>">
		<input type="date" name="dateEnd" value="<?= date("Y-m-d") ?>">
		<button type="button" class="w3-green submit" id="btnDate">Gửi</button>
	</div>
</div>

<div class="w3-responsive">
	<table id="table-show" class="w3-table-all">
		<thead>
		  	<tr class="w3-blue">
				<th>STT</th>
				<?php if ($this->view->duocXoa) { echo "<th>Xóa</th>";} ?>
				<th><a class="orderColumn" onclick="orderBy(this)">Chi Cho Ai
					<input type="hidden" name="chiChoAi" value="chiChoAi ASC">
					</a>
				</th>
				<th class="w3-center"><a class="orderColumn" onclick="orderBy(this)">Số Tiền Chi
					<input type="hidden" name="soTienChi" value="soTienChi ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Lý Do Chi
					<input type="hidden" name="lyDoChi" value="lyDoChi ASC">
					</a>
				</th>
				<th><a class="orderColumn width150px" onclick="orderBy(this)">Loại Chi Phí
					<input type="hidden" name="loaiChiPhi" value="loaiChiPhi ASC">
					</a>
				</th>
				<th><a class="orderColumn width100px" onclick="orderBy(this)">Ngày
					<input type="hidden" name="Ngay" value="Ngay ASC">
					</a>
				</th>
				<th><a class="orderColumn width100px" onclick="orderBy(this)">Hoàn Tất
					<input type="hidden" name="trangThai" value="trangThai ASC">
					</a>
				</th>
				<th><a class="orderColumn width100px" onclick="orderBy(this)">Người Nhập
					<input type="hidden" name="name" value="name ASC">
					</a>
				</th>
				<th></th>
		  	</tr>
		</thead>
		<tbody class="tbody">
		
		</tbody>
		
		<tfoot>
	        <tr>
	            <td colspan="11" align="right">
					<div class="w3-bar w3-center" id="pagination">
						
					</div>
	            </td>
	        </tr>
	    </tfoot>
	</table>

</div>
<div class="w3-row">
	<div class="w3-right-align" style="background: #000;padding: 10px;color: #fff">
		<b>Tổng Tiền:</b> <span class='tongTienChiPhi'></span>
	</div>
</div>
