<div class="w3-row padding-bottom10px padding-top10px">
	<input type="hidden" value="<?= $this->url->get('ghichu/index') ?>" id="linkIndex">
	<input type="hidden" value="<?= $this->url->get('ghichu/ajaxSearch') ?>" id="linkSendAjax">
	<input type="hidden" value="<?= $this->url->get('ghichu/edit/') ?>" id="linkEdit">
	<input type="hidden" value="<?= $this->url->get('ghichu/delete/') ?>" id="linkDelete">
	<input type="hidden" value="<?= $this->url->get('ghichu/ajaxTrangThai') ?>" id="linkAjaxTrangThai">

	<div class="w3-col l2 m2 s2 filter-limit">
		
		<span class="name-filter">Limit:</span>
		
		<?php 
		$limtSelector = new Phalcon\Forms\Element\Select('limit', [
				"25" 		=> "25",
				"50"  		=> "50",
				"100"  		=> "100",
				"200" 		=> "200",
				"500" 		=> "500",
				"1000" 		=> "1,000",
		], ['using'    => ["id", "name"] ]);
		
		$limtSelector->setDefault($limit);
		
		echo $limtSelector->render();
		?>
	</div>
	<div class="w3-col l5 m5 s10 filter-search">
		<span class="name-filter">Filter: </span> 
		<input type="search" name="filterRows" value="<?= $filterRows; ?>" placeholder="Search this table">
		<button type="button" id="btnResetFilter" class="buttonX">x</button>
		<button type="submit" class="w3-green submit" id="btnFilter">Filter</button>
	</div>
</div>

<div class="w3-responsive">
	<table id="table-show" class="w3-table-all">
		<thead>
		  	<tr class="w3-blue">
				<th>STT</th>
				<?php if ($this->view->duocXoa) { echo "<th>Xóa</th>";} ?>
				<th><a class="orderColumn" onclick="orderBy(this)">Ngày
					<input type="hidden" name="ngay" value="ngay ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Tiêu Đề
					<input type="hidden" name="tieuDe" value="tieuDe ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Nội Dung
					<input type="hidden" name="noiDung" value="noiDung ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Trạng Thái
					<input type="hidden" name="trangThai" value="trangThai ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Chế Độ
					<input type="hidden" name="cheDo" value="cheDo ASC">
					</a>
				</th>
		  	</tr>
		</thead>
		<tbody class="tbody">
		
		</tbody>

		<tfoot>
	        <tr>
	            <td colspan="7" align="right">
					<div class="w3-bar w3-center" id="pagination">
						
					</div>
	            </td>
	        </tr>
	    </tfoot>
	</table>
</div>