<div class="w3-row padding-bottom10px padding-top10px">
	<input type="hidden" value="<?= $this->url->get('nhansu/index') ?>" id="linkIndex">
	<input type="hidden" value="<?= $this->url->get('nhansu/ajaxSearch') ?>" id="linkSendAjax">
	<input type="hidden" value="<?= $this->url->get('nhansu/edit/') ?>" id="linkEdit">
	<input type="hidden" value="<?= $this->url->get('nhansu/delete/') ?>" id="linkDelete">
	<div class="w3-col l2 m2 s2 filter-limit">
		
		<span class="name-filter">Limit:</span>
		
		<?php 
		$limtSelector = new Phalcon\Forms\Element\Select('limit', [
				"25" 		=> "25",
				"50"  		=> "50",
				"100"  		=> "100",
				"200" 		=> "200",
				"500" 		=> "500",
				"1000" 		=> "1,000",
		], ['using'    => ["id", "name"] ]);
		
		$limtSelector->setDefault($limit);
		
		echo $limtSelector->render();
		?>
	</div>
	<div class="w3-col l5 m5 s10 filter-search">
		<span class="name-filter">Filter: </span> 
		<input type="search" name="filterRows" value="<?= $filterRows; ?>" placeholder="Search this table">
		<button type="button" id="btnResetFilter" class="buttonX">x</button>
		<button type="submit" class="w3-green submit" id="btnFilter">Filter</button>
	</div>
</div>

<div class="w3-responsive">
	<table id="table-show" class="w3-table-all">
		<thead>
		  	<tr class="w3-blue">
				<th>STT</th>
				<?php if ($this->view->duocXoa) { echo "<th>Xóa</th>";} ?>
				<th><a class="orderColumn" onclick="orderBy(this)">Họ Và Tên
					<input type="hidden" name="hoTen" value="hoTen ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">CMND
					<input type="hidden" name="CMND" value="CMND ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Ngày Sinh
					<input type="hidden" name="ngaySinh" value="ngaySinh ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Số Điện Thoại
					<input type="hidden" name="SDT" value="SDT ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Địa Chỉ
					<input type="hidden" name="diaChi" value="diaChi ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Quê Quán
					<input type="hidden" name="queQuan" value="queQuan ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Chức Vụ
					<input type="hidden" name="chucVu" value="chucVu ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Ghi Chú
					<input type="hidden" name="ghiChu" value="ghiChu ASC">
					</a>
				</th>	
		  	</tr>
		</thead>
		<tbody class="tbody">
		
		</tbody>

		<tfoot>
	        <tr>
	            <td colspan="11" align="right">
					<div class="w3-bar w3-center" id="pagination">
						
					</div>
	            </td>
	        </tr>
	    </tfoot>
	</table>
</div>