<div class="w3-row padding-bottom10px padding-top10px">
	<input type="hidden" value="<?= $this->url->get('products/index') ?>" id="linkIndex">
	<input type="hidden" value="<?= $this->url->get('products/ajaxSearch') ?>" id="linkSendAjax">
	<input type="hidden" value="<?= $this->url->get('products/edit/') ?>" id="linkEdit">
	<input type="hidden" value="<?= $this->url->get('products/delete/') ?>" id="linkDelete">
	<div class="w3-col l2 m2 s2 filter-limit">
		
		<span class="name-filter">Limit:</span>
		
		<?php 
		$limtSelector = new Phalcon\Forms\Element\Select('limit', [
				"25" 		=> "25",
				"50"  		=> "50",
				"100"  		=> "100",
				"200" 		=> "200",
				"500" 		=> "500",
				"1000" 		=> "1,000",
		], ['using'    => ["id", "name"] ]);
		
		$limtSelector->setDefault($limit);
		
		echo $limtSelector->render();
		?>
	</div>
	<div class="w3-col l5 m5 s10 filter-search">
		<span class="name-filter">Filter: </span>
		<input type="search" name="filterRows" value="<?= $filterRows; ?>" placeholder="Search this table">
		<button type="button" id="btnResetFilter" class="buttonX">x</button>
		<button type="submit" class="w3-green submit" id="btnFilter">Filter</button>
	</div>
	<div class="w3-col l2 m2">
		<label for="">Nổi Bật</label>
		<input type="checkbox" name="checkNoiBat" id="checkNoiBat" value="1" class="w3-check">
	</div>
</div>

<div class="w3-responsive">
	<table id="table-show" class="w3-table-all">
		<thead>
		  	<tr class="w3-blue">
				<th>STT</th>
				<?php if ($this->view->duocXoa) { echo "<th>Xóa</th>";} ?>
				<th><a class="orderColumn" onclick="orderBy(this)">Mã SP
					<input type="hidden" name="maSanPham" value="maSanPham ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Tên Sản Phẩm
					<input type="hidden" name="tenSanPham" value="tenSanPham ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Tồn H.tại
					<input type="hidden" name="tonHienTai" value="tonHienTai ASC">
					</a>
				</th>
				<?php if ($this->view->duocXoa): ?>
					<th class="w3-center"><a class="orderColumn" onclick="orderBy(this)">Đơn Giá Gốc
						<input type="hidden" name="donGiaMuaVao" value="donGiaMuaVao ASC">
						</a>
					</th>
				<?php endif ?>
				<th class="w3-center"><a class="orderColumn" onclick="orderBy(this)">Đơn Giá Mới Nhất
					<input type="hidden" name="donGiaMoiNhat" value="donGiaMoiNhat ASC">
					</a>
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Loại Sản Phẩm
					<input type="hidden" name="loaiSanPham" value="type ASC">
					</a>	
				</th>
				<th><a class="orderColumn" onclick="orderBy(this)">Tồn Kho Ban Đầu
					<input type="hidden" name="tonKhoBanDau" value="tonKhoBanDau ASC">
					</a>
				</th>
				<?php if ($this->view->duocXoa): ?>
					<th><a class="orderColumn" onclick="orderBy(this)">GT
						<input type="hidden" name="gt" value="gt ASC">
						</a>
					</th>
				<?php endif ?>
		  	</tr>
		</thead>
		<tbody class="tbody">
		
		</tbody>
		<tfoot>
	        <tr>
	            <td colspan="9" align="right">
					<div class="w3-bar w3-center" id="pagination">
						
					</div>
	            </td>
	        </tr>
	    </tfoot>
	</table>
</div>

<?php if ($this->view->duocXoa): ?>
	<div class="w3-row">
		<div class="w3-right-align" style="background: #000;padding: 10px;color: #fff">
			<b>Tổng Tiền:</b> <span class='tongTienProduct'></span>
		</div>
	</div>
<?php endif ?>